In [1]:
import os
import sys
import pandas as pd

In [7]:
print("System Version" + sys.version)
#print("Panda Version is"+pd.show_versions) ## Show version is a function
print("Pandas Version is " + pd.__version__)

System Version3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Pandas Version is 2.3.3

In [8]:
os.getcwd()

'C:\\Users\\ADMIN'

In [9]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [28]:
names=['Radha','Lakshmi','Lalitha','Seeta','Ishani','Ishika','Sreedevi']
age=[12,23,5,12,1,2,3]
DataSet=list(zip(names,age))
print(DataSet)

for names,age in DataSet:
   print(f"{names} is {age} years of age")

[('Radha', 12), ('Lakshmi', 23), ('Lalitha', 5), ('Seeta', 12), ('Ishani', 1), ('Ishika', 2), ('Sreedevi', 3)]
Radha is 12 years of age
Lakshmi is 23 years of age
Lalitha is 5 years of age
Seeta is 12 years of age
Ishani is 1 years of age
Ishika is 2 years of age
Sreedevi is 3 years of age

In [32]:
df=pd.DataFrame(data=DataSet,columns=['Names','Age'])
df
#print(df)

      Names  Age
0     Radha   12
1   Lakshmi   23
2   Lalitha    5
3     Seeta   12
4    Ishani    1
5    Ishika    2
6  Sreedevi    3


names = ["Alice", "Bob", "Charlie"]
age = [25, 30, 22]
DataSet=list(zip(names,age))
print(DataSet)

for name,age in DataSet:
    print(f'{name} is {age} years old')